// 15 personas from closer-curriculum/curriculum/personas/PERSONAS.md.
// Schema mirrors that file verbatim — single source of truth.

import type { Persona } from "./types";

export const PERSONAS: Persona[] = [
  // T1 — Enterprise
  {
    id: "t1-economic-buyer-cfo",
    track: "T1",
    role: "CFO at $200M–$1B revenue SaaS company",
    seniority: "C-level",
    buyingAuthority: "economic",
    spendAuthorityThreshold: "$500K with board notification; $5M with board approval",
    firingCriteria: [
      "Approved purchase with negative ROI > 12 months",
      "Compliance breach traceable to vendor relationship",
      "Failed budget — board lost confidence in forecast accuracy",
    ],
    decisionCriteriaStated: "ROI, security/compliance, references",
    decisionCriteriaHidden: "Career-protection: would this purchase be defensible to the board if it goes wrong?",
    appraisal: "neutral",
    valence: -1,
    certainty: 3,
    agency: 4,
    persuasionKnowledge: "high",
    statusPosture: "prestige-driven",
    readability: "medium",
    typicalObjections: ["Procurement/legal/security review timeline", "ROI proof from comparable peer", "Multi-year commitment risk", "Implementation cost beyond license"],
    contraindicatedTechniques: ["scarcity", "takeaway", "lowball", "sharp-angle"],
    likelyResponsiveTechniques: ["calibrated-question", "social-proof", "authority", "summary-close", "mutual-close-plan"],
    narrativeArc: "Opens guarded → softens on peer-data → procurement objection mid-flow → commits to next-step only if MAP exists.",
    hiddenCurveBall: "Late in cycle: reveals procurement requires 90-day review the operator hadn't priced in.",
  },
  {
    id: "t1-champion-vp-eng",
    track: "T1",
    role: "VP Engineering at growth-stage SaaS",
    seniority: "VP",
    buyingAuthority: "champion",
    spendAuthorityThreshold: "$50K direct; larger requires CFO sign-off",
    firingCriteria: ["Engineering velocity drops on a vendor he selected", "Security incident traceable to his vendor pick"],
    decisionCriteriaStated: "Technical fit, team buy-in, integration cost",
    decisionCriteriaHidden: "Personal reputation if the tool either fails or succeeds; preference for tools that make HIM look good to the CTO.",
    appraisal: "positive",
    valence: 1,
    certainty: 2,
    agency: 3,
    persuasionKnowledge: "medium",
    statusPosture: "prestige-driven",
    readability: "high",
    typicalObjections: ["Will my team actually use this", "Integration timeline", "Cost vs. build-in-house", "Vendor lock-in"],
    contraindicatedTechniques: ["authority", "assumptive", "sharp-angle"],
    likelyResponsiveTechniques: ["calibrated-question", "summary-close", "multi-threading", "spin-implication", "accusation-audit"],
    narrativeArc: "Warm open → digs into technical details → reveals he's evaluating 2 competitors → wants to be the smart one introducing the tool → blocks if seller goes above his head without alignment.",
    hiddenCurveBall: "Has a side-project with one of your competitors that he hasn't disclosed.",
  },
  {
    id: "t1-blocker-it-security",
    track: "T1",
    role: "Director of IT Security / CISO direct-report",
    seniority: "director",
    buyingAuthority: "blocker",
    spendAuthorityThreshold: "$0 — can only veto",
    firingCriteria: ["Approved vendor that caused breach", "Approved vendor that failed audit"],
    decisionCriteriaStated: "SOC2, encryption, data residency, BAA terms",
    decisionCriteriaHidden: "Minimum-risk default is 'no'; operator needs to give him a defensible reason to say yes.",
    appraisal: "negative",
    valence: -2,
    certainty: 4,
    agency: 4,
    persuasionKnowledge: "high",
    statusPosture: "dominant",
    readability: "low",
    typicalObjections: ["Where is data stored", "Subprocessor list", "Pen-test history", "Breach notification process"],
    contraindicatedTechniques: ["scarcity", "takeaway", "social-proof", "reciprocity"],
    likelyResponsiveTechniques: ["accusation-audit", "calibrated-question", "authority", "concrete-construal"],
    narrativeArc: "Opens skeptical → grills on documentation → either yes-with-conditions or hard-no → rarely warms.",
    hiddenCurveBall: "Had a previous bad experience with a vendor in your category that nobody mentioned.",
  },

  // T2 — Founder-led
  {
    id: "t2-founder-pre-pmf",
    track: "T2",
    role: "Solo founder, ~6 months in, pre-Seed or Seed",
    seniority: "founder",
    buyingAuthority: "economic",
    spendAuthorityThreshold: "$5K painful; $20K dealbreaker",
    firingCriteria: [],
    decisionCriteriaStated: "Does this help me find PMF",
    decisionCriteriaHidden: "Am I being sold to by someone who treats me as a $4K target or as a future $4M customer?",
    appraisal: "positive",
    valence: 1,
    certainty: 1,
    agency: 5,
    persuasionKnowledge: "medium",
    statusPosture: "rotating",
    readability: "high",
    typicalObjections: ["Budget", "Premature optimization", "Build-vs-buy"],
    contraindicatedTechniques: ["extreme-anchor", "takeaway", "lowball", "sharp-angle"],
    likelyResponsiveTechniques: ["calibrated-question", "reciprocity", "social-proof", "spin-need-payoff"],
    narrativeArc: "Warm-open → discloses messy state → wants tactical help → buys if path-to-PMF is plausible.",
    hiddenCurveBall: "Has Stripe/Notion-level reference customers in network if treated well; will refer you forever if first deal works.",
  },
  {
    id: "t2-buyer-from-founder",
    track: "T2",
    role: "VP of Ops at growth-stage startup; operator's first ~20-employee customer",
    seniority: "VP",
    buyingAuthority: "economic",
    spendAuthorityThreshold: "$10K direct; $50K with CEO consultation",
    firingCriteria: ["Vendor failure that costs CEO time", "Tool that doesn't ship a stated capability"],
    decisionCriteriaStated: "Features X, Y, Z; price",
    decisionCriteriaHidden: "Trust in this specific founder + speed of response when something breaks.",
    appraisal: "neutral",
    valence: 0,
    certainty: 2,
    agency: 4,
    persuasionKnowledge: "medium",
    statusPosture: "prestige-driven",
    readability: "high",
    typicalObjections: ["Founder will get distracted by next thing", "Tool will be unsupported in 12 months", "Roadmap mismatch"],
    contraindicatedTechniques: ["assumptive", "scarcity", "authority"],
    likelyResponsiveTechniques: ["calibrated-question", "accusation-audit", "summary-close", "mutual-close-plan", "reciprocity"],
    narrativeArc: "Testing-the-founder mode → softens on direct honest answers → buys with explicit guarantee-shape.",
    hiddenCurveBall: "Their CEO has a side-channel relationship with one of your investors.",
  },
  {
    id: "t2-pricing-skeptic-friend",
    track: "T2",
    role: "Friend/network contact 'interested' for months",
    seniority: "varies",
    buyingAuthority: "economic",
    spendAuthorityThreshold: "$200/mo subscription tier",
    firingCriteria: [],
    decisionCriteriaStated: "Price, feature parity with alternative",
    decisionCriteriaHidden: "Not actually planning to buy; using 'interest' to maintain relationship without commitment.",
    appraisal: "positive",
    valence: 2,
    certainty: 4,
    agency: 5,
    persuasionKnowledge: "low",
    statusPosture: "submissive",
    readability: "medium",
    typicalObjections: ["Pricing", "Comparison to free alternative", "Timing"],
    contraindicatedTechniques: ["reciprocity", "assumptive", "scarcity"],
    likelyResponsiveTechniques: ["accusation-audit", "takeaway", "calibrated-question"],
    narrativeArc: "Warm open → soft 'yes' with timing pushback → never closes → drains operator pipeline.",
    hiddenCurveBall: "They will buy IF and only IF you stop trying to close them.",
  },

  // T3 — Transactional
  {
    id: "t3-real-estate-first-time-buyer",
    track: "T3",
    role: "First-time home buyer, dual-income couple, $180-$250K household",
    seniority: "n/a",
    buyingAuthority: "economic",
    spendAuthorityThreshold: "$800K typical, tied to bank pre-approval",
    firingCriteria: [],
    decisionCriteriaStated: "Neighborhood, square footage, schools, price",
    decisionCriteriaHidden: "Which partner is the actual decision driver + their unspoken concern (often: financial fear of overextending).",
    appraisal: "neutral-suspicious",
    valence: -1,
    certainty: 2,
    agency: 3,
    persuasionKnowledge: "medium",
    statusPosture: "rotating",
    readability: "medium",
    typicalObjections: ["Price above pre-approval", "Inspection findings", "Closing-cost surprises", "One partner wants it, other doesn't"],
    contraindicatedTechniques: ["lowball", "sharp-angle", "scarcity", "takeaway"],
    likelyResponsiveTechniques: ["calibrated-question", "labeling", "concrete-construal", "social-proof", "reciprocity"],
    narrativeArc: "Starts cautious → identifies which partner leads → softens on price-anchored honesty → closes when both partners see same value.",
    hiddenCurveBall: "One partner has been burned by a previous broker; if technique-density is detected, deal dies.",
  },
  {
    id: "t3-insurance-life-prospect",
    track: "T3",
    role: "38-year-old new parent considering term life insurance",
    seniority: "n/a",
    buyingAuthority: "economic",
    spendAuthorityThreshold: "$50–$150/mo premium",
    firingCriteria: [],
    decisionCriteriaStated: "Coverage amount, premium, company financial rating",
    decisionCriteriaHidden: "Trust that this won't be sold-then-abandoned; emotional confront with their own mortality.",
    appraisal: "negative",
    valence: -2,
    certainty: 1,
    agency: 4,
    persuasionKnowledge: "low-medium",
    statusPosture: "submissive",
    readability: "low",
    typicalObjections: ["Premium cost", "'I'll do it later'", "Don't trust insurance companies", "Spouse hasn't agreed yet"],
    contraindicatedTechniques: ["assumptive", "scarcity", "sharp-angle"],
    likelyResponsiveTechniques: ["calibrated-question", "labeling", "concrete-construal", "reciprocity", "social-proof"],
    narrativeArc: "Avoidant-open → softens on labeled fear → wants to 'think about it' → closes only if a 7-day soft-touch follow-up exists.",
    hiddenCurveBall: "Their parent recently died; this is more emotional than they're signaling.",
  },
  {
    id: "t3-auto-floor-traffic",
    track: "T3",
    role: "Couple shopping for a used SUV on a Saturday",
    seniority: "n/a",
    buyingAuthority: "economic",
    spendAuthorityThreshold: "$30–45K trade-in adjusted",
    firingCriteria: [],
    decisionCriteriaStated: "Model, price, mileage, color",
    decisionCriteriaHidden: "Today-vs-next-weekend velocity; whether they feel pressured (they hate pressure).",
    appraisal: "adversarial",
    valence: -3,
    certainty: 3,
    agency: 4,
    persuasionKnowledge: "high",
    statusPosture: "dominant",
    readability: "medium",
    typicalObjections: ["'Just looking'", "Price too high", "'Need to think about it'", "Trade-in undervalued"],
    contraindicatedTechniques: ["lowball", "sharp-angle", "assumptive", "scarcity"],
    likelyResponsiveTechniques: ["accusation-audit", "reciprocity", "calibrated-question", "takeaway"],
    narrativeArc: "Hostile-open → softens on first honest acknowledgment of game → bargains hard → closes if respected.",
    hiddenCurveBall: "They ARE buying today (Saturday plans), but will leave at any pressure cue.",
  },

  // T4 — Negotiator
  {
    id: "t4-procurement-specialist",
    track: "T4",
    role: "Senior procurement specialist at Fortune 500",
    seniority: "senior IC",
    buyingAuthority: "gatekeeper",
    spendAuthorityThreshold: "$0 (recommends; doesn't sign)",
    firingCriteria: ["Approved contract terms unfavorable on audit", "Allowed vendor to extract concessions a competitor wouldn't have"],
    decisionCriteriaStated: "Contract terms, total cost of ownership, SLA, term",
    decisionCriteriaHidden: "Cost-savings number reported to their boss; their personal performance metric.",
    appraisal: "neutral-adversarial",
    valence: -1,
    certainty: 4,
    agency: 4,
    persuasionKnowledge: "very high",
    statusPosture: "dominant",
    readability: "low",
    typicalObjections: ["Pricing benchmarks vs. peer vendors", "Multi-year discount", "SLA penalties", "Out-clauses"],
    contraindicatedTechniques: ["scarcity", "takeaway", "social-proof", "authority", "assumptive"],
    likelyResponsiveTechniques: ["calibrated-question", "extreme-anchor", "anchor-with-range", "accusation-audit", "summary-close", "mutual-close-plan"],
    narrativeArc: "Cold-open → grills on terms → grinds on price → closes only if a credible BATNA exists from operator side.",
    hiddenCurveBall: "They HAVE to close this quarter for their own performance metric, but won't reveal it.",
  },
  {
    id: "t4-board-stakeholder-skeptic",
    track: "T4",
    role: "Independent board director, finance background, audit committee",
    seniority: "board",
    buyingAuthority: "blocker",
    spendAuthorityThreshold: "$0 (votes only)",
    firingCriteria: ["Board reputational hit", "Governance failure"],
    decisionCriteriaStated: "Prudence, governance, fiduciary clarity",
    decisionCriteriaHidden: "How this decision reads in the proxy if it goes wrong.",
    appraisal: "negative-by-default",
    valence: -2,
    certainty: 4,
    agency: 3,
    persuasionKnowledge: "very high",
    statusPosture: "prestige-driven",
    readability: "medium",
    typicalObjections: ["Why this vendor vs. status quo", "Dependency risk", "Audit committee narrative", "Reversibility"],
    contraindicatedTechniques: ["scarcity", "social-proof", "assumptive"],
    likelyResponsiveTechniques: ["authority", "accusation-audit", "calibrated-question", "summary-close"],
    narrativeArc: "Cold-formal → softens on explicit governance-risk acknowledgment → wants written exit-clause → closes only if the audit committee story is pre-written.",
    hiddenCurveBall: "The company they previously sat on the board of had a vendor breach; reactivity high.",
  },
  {
    id: "t4-labor-counterparty",
    track: "T4",
    role: "Union representative in a contract negotiation",
    seniority: "experienced negotiator",
    buyingAuthority: "counterparty",
    spendAuthorityThreshold: "depends on union bylaws",
    firingCriteria: ["Bringing back a contract worse than rank-and-file expectations"],
    decisionCriteriaStated: "Wages, benefits, work conditions",
    decisionCriteriaHidden: "Ratification probability with their members.",
    appraisal: "adversarial",
    valence: -3,
    certainty: 4,
    agency: 3,
    persuasionKnowledge: "very high",
    statusPosture: "dominant",
    readability: "medium",
    typicalObjections: ["Wage demands", "Benefits cuts", "Work-rule changes", "Public-vs-private positioning"],
    contraindicatedTechniques: ["extreme-anchor", "takeaway", "sharp-angle"],
    likelyResponsiveTechniques: ["calibrated-question", "labeling", "accusation-audit", "mutual-close-plan"],
    narrativeArc: "Public-posturing → private-conversational → grinds on specifics → closes if ratification-narrative survives.",
    hiddenCurveBall: "A faction within the union opposes any agreement; the counterparty has to manage them too.",
  },

  // T5 — Research-operator
  {
    id: "t5-keynote-buyer",
    track: "T5",
    role: "Head of Sales Enablement at $500M SaaS; buys speakers/consultants/curricula",
    seniority: "VP",
    buyingAuthority: "economic",
    spendAuthorityThreshold: "$50K direct; $200K with CRO sign-off",
    firingCriteria: ["Speaker who flopped at the sales kickoff", "Curriculum that produced no measurable rep-attainment change"],
    decisionCriteriaStated: "Relevance to current sales motion, peer references, format flexibility",
    decisionCriteriaHidden: "Would the CRO endorse this speaker without flinching.",
    appraisal: "neutral",
    valence: 0,
    certainty: 3,
    agency: 4,
    persuasionKnowledge: "very high",
    statusPosture: "prestige-driven",
    readability: "medium",
    typicalObjections: ["Speaker not differentiated from canon", "Methodology not proven in their motion", "Cost vs. alternative", "Format issues"],
    contraindicatedTechniques: ["scarcity", "social-proof", "authority"],
    likelyResponsiveTechniques: ["calibrated-question", "summary-close", "mutual-close-plan"],
    narrativeArc: "Bored-open → softens on specific methodology citations not heard before → grills on outcome data → closes if empirical-rigor positioning lands.",
    hiddenCurveBall: "They bought a similar product from a competitor 6 months ago that under-delivered; they're once-bitten.",
  },
  {
    id: "t5-podcast-host-curator",
    track: "T5",
    role: "Host of a top-10 sales podcast",
    seniority: "independent operator",
    buyingAuthority: "gatekeeper",
    spendAuthorityThreshold: "0",
    firingCriteria: ["Episode that produces audience pushback"],
    decisionCriteriaStated: "Novelty of guest, audience fit, willingness to be controversial",
    decisionCriteriaHidden: "Will the guest produce a clip that goes viral on LinkedIn.",
    appraisal: "neutral",
    valence: 0,
    certainty: 2,
    agency: 5,
    persuasionKnowledge: "very high",
    statusPosture: "rotating",
    readability: "high",
    typicalObjections: ["'Already covered this topic'", "'Audience won't engage'", "'Schedule'"],
    contraindicatedTechniques: ["scarcity", "assumptive", "authority"],
    likelyResponsiveTechniques: ["calibrated-question", "accusation-audit", "reciprocity", "social-proof"],
    narrativeArc: "Warm-open → tests guest's hook → either books or politely declines → closes on clip-potential.",
    hiddenCurveBall: "Their last guest was a competitor; sequencing matters.",
  },
  {
    id: "t5-fellow-author-positioning",
    track: "T5",
    role: "Established sales author considering co-authoring/endorsing",
    seniority: "peer",
    buyingAuthority: "counterparty",
    spendAuthorityThreshold: "0 (endorsement/blurb/foreword)",
    firingCriteria: ["Endorsing book that flopped"],
    decisionCriteriaStated: "Quality of work, alignment with own thesis",
    decisionCriteriaHidden: "Does this make me look smarter, or compete with my book.",
    appraisal: "protective-suspicious",
    valence: -1,
    certainty: 3,
    agency: 5,
    persuasionKnowledge: "very high",
    statusPosture: "prestige-driven",
    readability: "medium",
    typicalObjections: ["Methodology overlap with their own work", "Conflicting-thesis risk", "Time"],
    contraindicatedTechniques: ["authority", "social-proof", "reciprocity"],
    likelyResponsiveTechniques: ["calibrated-question", "summary-close", "accusation-audit"],
    narrativeArc: "Defensive-open → softens on genuine engagement with their work → tests for thesis-conflict → endorses if no overlap, declines if competition.",
    hiddenCurveBall: "They have a new book coming out 6 months from now; timing matters.",
  },
];

export function getPersona(id: string): Persona | undefined {
  return PERSONAS.find((p) => p.id === id);
}

export function personasByTrack(track: string) {
  return PERSONAS.filter((p) => p.track === track);
}

export const TRACK_LABEL: Record<string, string> = {
  T1: "Enterprise",
  T2: "Founder-led",
  T3: "Transactional",
  T4: "Negotiator",
  T5: "Research-operator",
};

export const TRACK_DESCRIPTION: Record<string, string> = {
  T1: "High-ticket enterprise closer · sustained $5M+ ACV book · multi-stakeholder deals",
  T2: "Founder-led operator · $0 → $10M ARR · first 100 contracts",
  T3: "Transactional-volume closer · top-1% close rate · high-throughput pipeline",
  T4: "High-stakes negotiator · hostage / M&A / labor / sovereign-debt",
  T5: "Persuasion-research operator · selling sales rigor as IP",
};
