// 35 Atlas-taxonomy techniques.
// Source: closer-curriculum/research/layers/L4-technique/atlas-crossref.md (v0.1, locked).

import type { Technique } from "./types";

export const TECHNIQUES: Technique[] = [
  // A · Compliance-gaining
  { id: "fitd", name: "Foot-in-the-door", cluster: "compliance", mechanism: "Small initial compliance creates self-perception of being a compliant person; subsequent larger request is harder to refuse without identity inconsistency.", atlasVerdict: "well-studied", folkloreRisk: "low", canonicalSource: "Cialdini 1984; Freedman & Fraser 1966", primaryFailureMode: "Reverse-causation: in commercial repeat-game contexts, the small ask can poison the target if perceived as transactional.", contraindication: "Single-shot consumer contexts where the target sees you only once; identity-relevance must hold.", stageRouting: ["S3", "S4", "S5"] },
  { id: "ditf", name: "Door-in-the-face", cluster: "compliance", mechanism: "Large initial request creates perception of concession when retreating to target; reciprocity norm activated.", atlasVerdict: "partially-studied", folkloreRisk: "medium", canonicalSource: "Cialdini 1984; O'Keefe & Hale 1998", primaryFailureMode: "Initial request implausible enough to insult; technique reads as manipulation.", contraindication: "Procurement specialists or persuasion-knowledge-high buyers.", stageRouting: ["S3", "S4"] },
  { id: "lowball", name: "Low-ball", cluster: "compliance", mechanism: "Initial small commitment binds participant; raised price after commitment is harder to refuse than same price offered initially.", atlasVerdict: "partially-studied", folkloreRisk: "medium-high", canonicalSource: "Cialdini et al. 1978", primaryFailureMode: "Catastrophic in repeat-game; experienced as deception at renewal.", contraindication: "ANY repeat-game commercial context. Ethics-flagged.", stageRouting: ["S3"] },
  { id: "tna", name: "That's-not-all", cluster: "compliance", mechanism: "Sequential added bonuses before counter-offer activates reciprocity and value-anchoring.", atlasVerdict: "partially-studied", folkloreRisk: "medium", canonicalSource: "Burger 1986", primaryFailureMode: "Density past buyer's perceived-fairness threshold reads as desperation.", contraindication: "Procurement; persuasion-knowledge-high buyers.", stageRouting: ["S3", "S4"] },
  { id: "disrupt-then-reframe", name: "Disrupt-then-reframe", cluster: "compliance", mechanism: "Unexpected pattern disruption creates micro-confusion; reframe in same breath bypasses critical evaluation.", atlasVerdict: "replication-failed", folkloreRisk: "high", canonicalSource: "Davis & Knowles 1999 (replication concerns: Carpenter 2013)", primaryFailureMode: "Original cupcake-study replication failed. Brittle technique.", contraindication: "Any context where the reframe doesn't survive the buyer's later reflection.", stageRouting: ["S3"] },

  // B · Cialdini six principles
  { id: "reciprocity", name: "Reciprocity", cluster: "cialdini", mechanism: "Norm of reciprocation creates obligation following unsolicited gift, favor, or concession.", atlasVerdict: "well-studied", folkloreRisk: "low", canonicalSource: "Cialdini 1984; Regan 1971", primaryFailureMode: "Over-leveraged reciprocity degrades into transactional perception.", contraindication: "Frequent gifts to same buyer; transparent transactional framing.", stageRouting: ["S3", "S4", "S5"] },
  { id: "scarcity", name: "Scarcity", cluster: "cialdini", mechanism: "Loss-aversion + reactance: limited availability raises perceived value and urgency.", atlasVerdict: "well-studied", folkloreRisk: "low-medium", canonicalSource: "Cialdini 1984", primaryFailureMode: "Manufactured scarcity detected = trust collapse + reactance.", contraindication: "Any context where scarcity claim is unverifiable or falsifiable.", stageRouting: ["S3", "S4", "S5"] },
  { id: "authority", name: "Authority cues", cluster: "cialdini", mechanism: "Heuristic deference to expertise/status reduces deliberation cost.", atlasVerdict: "partially-studied", folkloreRisk: "medium", canonicalSource: "Cialdini 1984; Milgram", primaryFailureMode: "Titular authority without specific expertise triggers persuasion-knowledge.", contraindication: "Specificity-of-credential is the discriminator; never claim titular.", stageRouting: ["S3", "S4"] },
  { id: "social-proof", name: "Social proof", cluster: "cialdini", mechanism: "Uncertainty resolved by observing others' behavior; conformity heuristic activates.", atlasVerdict: "well-studied", folkloreRisk: "low", canonicalSource: "Cialdini 1984; Deutsch & Gerard 1955", primaryFailureMode: "Generic social-proof ('thousands of customers') has low specificity-effect.", contraindication: "When peer set is dissimilar to buyer; named peers in same industry/role/stage carry weight.", stageRouting: ["S3", "S4", "S5"] },
  { id: "liking", name: "Liking / similarity / rapport", cluster: "cialdini", mechanism: "Affect transfer from liked source to evaluated offer; similarity activates in-group cooperative heuristics.", atlasVerdict: "partially-studied", folkloreRisk: "medium", canonicalSource: "Cialdini 1984", primaryFailureMode: "Confusing warmth-of-interaction with accuracy-of-other-model.", contraindication: "Never substitute liking for understanding (L3 F12).", stageRouting: ["S3", "S4"] },
  { id: "commitment-consistency", name: "Commitment & consistency", cluster: "cialdini", mechanism: "Prior public stance creates pressure to act consistently.", atlasVerdict: "partially-studied", folkloreRisk: "medium", canonicalSource: "Cialdini 1984; SPIN (Rackham 1988)", primaryFailureMode: "Public+written+effortful commitments compound the effect; lone verbal weak.", contraindication: "When buyer feels trapped rather than guided.", stageRouting: ["S3", "S4", "S5"] },

  // C · Framing
  { id: "loss-framing", name: "Loss-aversion framing", cluster: "framing", mechanism: "Asymmetric weighting of losses vs. gains; status-quo bias activated.", atlasVerdict: "well-studied", folkloreRisk: "low", canonicalSource: "Tversky & Kahneman 1981; Challenger Sale 2011", primaryFailureMode: "Over-deployed fear-frame triggers reactance.", contraindication: "Promotion-focused buyers (regulatory-fit mismatch).", stageRouting: ["S3", "S4", "S5"] },
  { id: "gain-framing", name: "Gain framing", cluster: "framing", mechanism: "Outcome-positive framing matches promotion-focus regulatory state.", atlasVerdict: "partially-studied", folkloreRisk: "medium", canonicalSource: "Higgins 1997", primaryFailureMode: "Heterogeneous by buyer's regulatory focus; not universal.", contraindication: "Prevention-focused buyers.", stageRouting: ["S3", "S4"] },
  { id: "regulatory-fit", name: "Regulatory fit", cluster: "framing", mechanism: "Matching buyer's regulatory focus (prevention vs. promotion) to message frame increases fluency and persuasion.", atlasVerdict: "well-studied", folkloreRisk: "low", canonicalSource: "Higgins 1997, 1998", primaryFailureMode: "Misdiagnosis of buyer's regulatory focus → frame inversion.", contraindication: "Requires accurate L3 read first.", stageRouting: ["S3", "S4", "S5"] },
  { id: "concrete-construal", name: "Concrete-vs-abstract framing", cluster: "framing", mechanism: "Psychologically-near framing matches near-construal of immediate decisions.", atlasVerdict: "well-studied", folkloreRisk: "low", canonicalSource: "Trope & Liberman 2010; Voss 2016", primaryFailureMode: "Abstract framing at decision moment fails.", contraindication: "Early discovery where buyer needs abstract orientation.", stageRouting: ["S3", "S4", "S5"] },

  // D · Structural close
  { id: "assumptive", name: "Assumptive close", cluster: "structural-close", mechanism: "Default-option psychology; reframes decision from 'if' to 'which'.", atlasVerdict: "untested-in-database", folkloreRisk: "high", canonicalSource: "Hopkins 1980; Tracy 1995", primaryFailureMode: "Folklore-risk-high. Felt-power inflates confidence in effect.", contraindication: "Most contexts pending Atlas-G3 verdict.", stageRouting: ["S3"] },
  { id: "alternative-choice", name: "Alternative-choice close", cluster: "structural-close", mechanism: "Narrows decision space; default option reduces overwhelm.", atlasVerdict: "untested-in-database", folkloreRisk: "high", canonicalSource: "Hopkins; Tracy", primaryFailureMode: "Folklore-risk-high.", contraindication: "When the two options are not both favorable to seller.", stageRouting: ["S3"] },
  { id: "summary-close", name: "Summary close", cluster: "structural-close", mechanism: "Explicit summary of agreed value reduces decision uncertainty.", atlasVerdict: "partially-studied", folkloreRisk: "low-medium", canonicalSource: "Hopkins; Rackham (SPIN); Dixon (Challenger)", primaryFailureMode: "Generic summary not mirroring buyer language.", contraindication: "When buyer hasn't yet articulated value criteria.", stageRouting: ["S3", "S4", "S5"] },
  { id: "trial-close", name: "Trial close", cluster: "structural-close", mechanism: "Elicits intermediate commitment; surfaces objections early.", atlasVerdict: "partially-studied", folkloreRisk: "medium", canonicalSource: "Hopkins; SPIN", primaryFailureMode: "Premature trial close before discovery complete.", contraindication: "Before qualification is established.", stageRouting: ["S3", "S4", "S5"] },
  { id: "takeaway", name: "Takeaway close", cluster: "structural-close", mechanism: "Activates reactance and loss aversion; creates pursuit dynamic.", atlasVerdict: "untested-in-database", folkloreRisk: "medium-high", canonicalSource: "Voss 2016; Belfort", primaryFailureMode: "Read as bluff when BATNA lacks credibility.", contraindication: "Without genuine BATNA. Procurement specialists.", stageRouting: ["S3", "S4"] },
  { id: "ben-franklin", name: "Ben Franklin close", cluster: "structural-close", mechanism: "Systematic enumeration favors seller's framing (more pros pre-loaded).", atlasVerdict: "untested-in-database", folkloreRisk: "high", canonicalSource: "Hopkins; Tracy", primaryFailureMode: "Folklore-risk-high. Vibes-heavy.", contraindication: "Sophisticated B2B buyers; reads as theater.", stageRouting: ["S3"] },
  { id: "puppy-dog", name: "Puppy-dog close", cluster: "structural-close", mechanism: "Endowment effect after possession.", atlasVerdict: "partially-studied", folkloreRisk: "low-medium", canonicalSource: "Hopkins; SaaS industry; endowment lit (Kahneman 1991)", primaryFailureMode: "Free-trial without onboarding produces churn not endowment.", contraindication: "When trial friction is high enough to prevent endowment.", stageRouting: ["S3", "S4", "S5"] },
  { id: "sharp-angle", name: "Sharp-angle close", cluster: "structural-close", mechanism: "Locks objection into commitment via conditional concession.", atlasVerdict: "untested-in-database", folkloreRisk: "high", canonicalSource: "Hopkins; Belfort", primaryFailureMode: "Folklore-risk-high. Ethics-flagged in repeat-game.", contraindication: "Any repeat-game context.", stageRouting: ["S3"] },

  // E · Question-form
  { id: "calibrated-question", name: "Calibrated question", cluster: "question-form", mechanism: "Open-ended how/what-stem invites buyer-generated elaboration; converts no-stance to problem-solving stance.", atlasVerdict: "well-studied", folkloreRisk: "low", canonicalSource: "Voss 2016; Miller & Rollnick 2012 (MI/OARS); Rackham 1988", primaryFailureMode: "Regression to leading-question phrasing under live pressure.", contraindication: "When direct factual answer was required.", stageRouting: ["S3", "S4", "S5"] },
  { id: "labeling", name: "Affect labeling", cluster: "question-form", mechanism: "Verbalizing emotion reduces amygdala activation; signals empathy.", atlasVerdict: "well-studied", folkloreRisk: "low", canonicalSource: "Voss 2016; Lieberman 2007", primaryFailureMode: "Scripted overuse ('it seems like…' 6+ times per call) triggers persuasion-knowledge.", contraindication: "Without genuine affect to label.", stageRouting: ["S3", "S4", "S5"] },
  { id: "mirroring", name: "Mirroring (verbal repetition)", cluster: "question-form", mechanism: "Last-3-words echo signals attention; minimal-encourager extends counterparty turn.", atlasVerdict: "partially-studied", folkloreRisk: "medium", canonicalSource: "Voss 2016", primaryFailureMode: "Echo-density triggers persuasion-knowledge.", contraindication: "When counterparty's last words don't invite elaboration.", stageRouting: ["S3", "S4"] },
  { id: "accusation-audit", name: "Accusation audit", cluster: "question-form", mechanism: "Preemptively naming buyer's likely objections inoculates against them.", atlasVerdict: "untested-in-database", folkloreRisk: "medium", canonicalSource: "Voss 2016", primaryFailureMode: "Wrong-axis accusation surfaces objection buyer didn't have.", contraindication: "When the accusation isn't actually being made.", stageRouting: ["S3", "S4"] },
  { id: "spin-implication", name: "SPIN implication question", cluster: "question-form", mechanism: "Elicits buyer-generated cost of the problem; raises perceived problem severity.", atlasVerdict: "partially-studied", folkloreRisk: "low-medium", canonicalSource: "Rackham 1988", primaryFailureMode: "Premature implication before problem is established.", contraindication: "Before buyer agrees a problem exists.", stageRouting: ["S3", "S4", "S5"] },
  { id: "spin-need-payoff", name: "SPIN need-payoff question", cluster: "question-form", mechanism: "Elicits buyer-generated benefits; pre-commits buyer to solution rationale.", atlasVerdict: "partially-studied", folkloreRisk: "low-medium", canonicalSource: "Rackham 1988", primaryFailureMode: "Asked before implication is felt → feels manipulative.", contraindication: "Before buyer feels the problem cost.", stageRouting: ["S3", "S4", "S5"] },

  // F · Negotiation-anchor
  { id: "extreme-anchor", name: "Extreme anchor", cluster: "negotiation-anchor", mechanism: "Initial number anchors counterparty's adjustment.", atlasVerdict: "well-studied", folkloreRisk: "low", canonicalSource: "Tversky & Kahneman 1974; Voss 2016; Galinsky", primaryFailureMode: "Anchor without BATNA produces walk-away.", contraindication: "Without credible BATNA.", stageRouting: ["S3", "S4", "S5"] },
  { id: "precise-anchor", name: "Precise number anchor", cluster: "negotiation-anchor", mechanism: "Precise numbers signal information; counterparty adjusts less.", atlasVerdict: "well-studied", folkloreRisk: "low", canonicalSource: "Mason et al. 2013", primaryFailureMode: "Over-precision when buyer hasn't accepted negotiation frame.", contraindication: "Before pricing discussion is open.", stageRouting: ["S3", "S4", "S5"] },
  { id: "anchor-with-range", name: "Range anchor", cluster: "negotiation-anchor", mechanism: "Range anchors with backed-bottom outperform point anchors.", atlasVerdict: "partially-studied", folkloreRisk: "low-medium", canonicalSource: "Ames & Mason 2015", primaryFailureMode: "Range too wide signals uncertainty.", contraindication: "Adversarial counterparty.", stageRouting: ["S3", "S4"] },
  { id: "bracketing", name: "Bracketing", cluster: "negotiation-anchor", mechanism: "Offers a range that brackets the target; counterparty meets in middle.", atlasVerdict: "untested-in-database", folkloreRisk: "medium", canonicalSource: "Voss 2016", primaryFailureMode: "Target visible to counterparty undermines effect.", contraindication: "When target inference is easy.", stageRouting: ["S3"] },

  // G · Post-objection
  { id: "feel-felt-found", name: "Feel-felt-found", cluster: "post-objection", mechanism: "Validates concern, then social-proof reframes.", atlasVerdict: "untested-in-database", folkloreRisk: "high", canonicalSource: "Hopkins; Tracy", primaryFailureMode: "Scripted-cliche risk; pattern recognized immediately.", contraindication: "Persuasion-knowledge-high buyers.", stageRouting: ["S3"] },
  { id: "isolate-and-conquer", name: "Isolate-the-objection", cluster: "post-objection", mechanism: "Elicits commitment that this is the only objection; remove it and commitment follows.", atlasVerdict: "untested-in-database", folkloreRisk: "medium", canonicalSource: "Sandler; Belfort", primaryFailureMode: "Buyer hides true objection.", contraindication: "When buyer has political reasons to surface false objection.", stageRouting: ["S3", "S4"] },
  { id: "reverse-objection", name: "Boomerang / reverse objection", cluster: "post-objection", mechanism: "Reframes objection as a reason to buy.", atlasVerdict: "untested-in-database", folkloreRisk: "high", canonicalSource: "Tracy", primaryFailureMode: "Brittle. Reads as denial.", contraindication: "Genuine deal-blocking objections.", stageRouting: ["S3"] },

  // H · Closing-environment
  { id: "silence", name: "Strategic silence after offer", cluster: "closing-environment", mechanism: "Discomfort-with-silence pushes counterparty to fill it (often with concession or commitment).", atlasVerdict: "untested-in-database", folkloreRisk: "medium", canonicalSource: "Sandler; Voss 2016", primaryFailureMode: "Broken too early (3s instead of 7s).", contraindication: "Across cultural contexts where silence is comfortable.", stageRouting: ["S3", "S4", "S5"] },
  { id: "mutual-close-plan", name: "Mutual close plan (MAP)", cluster: "closing-environment", mechanism: "Explicit shared timeline reduces stalls; multi-threading via named stakeholders.", atlasVerdict: "untested-in-database", folkloreRisk: "low-medium", canonicalSource: "MEDDIC / MEDDPICC; Force Management; commercial data (Gong/SBI)", primaryFailureMode: "MAP without exit-criteria becomes theater.", contraindication: "Single-stakeholder transactional deals.", stageRouting: ["S3", "S4", "S5"] },
  { id: "multi-threading", name: "Multi-threading", cluster: "closing-environment", mechanism: "Parallel relationships across stakeholders prevents single-point-of-failure on close.", atlasVerdict: "untested-in-database", folkloreRisk: "low-medium", canonicalSource: "Challenger Sale; MEDDIC; commercial data (CEB)", primaryFailureMode: "Multi-threading without champion installation = noise.", contraindication: "Transactional consumer contexts.", stageRouting: ["S3", "S4", "S5"] },
];

export function getTechnique(id: string): Technique | undefined {
  return TECHNIQUES.find((t) => t.id === id);
}

export function techniquesByCluster(cluster: string) {
  return TECHNIQUES.filter((t) => t.cluster === cluster);
}

export const ATLAS_VERDICT_LABEL: Record<string, string> = {
  "well-studied": "well-studied",
  "partially-studied": "partially-studied",
  "untested-in-database": "untested",
  "replication-failed": "replication-failed",
};

export const FOLKLORE_RISK_LABEL: Record<string, string> = {
  low: "low risk",
  "low-medium": "low-medium",
  medium: "medium",
  "medium-high": "medium-high",
  high: "high — recognition only",
};
